import { useGadget } from "@gadgetinc/react-shopify-app-bridge";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { SIZE, Spinner } from "baseui/spinner";
import { api } from "../lib/api";
import { useFindFirst } from "@gadgetinc/react";
import { Redirect } from "@shopify/app-bridge/actions";

const Finalized = () => {
  return <div>Thanks for signing up for Showday!</div>;
};

const Authenticated = () => {
  const [{ data, fetching }] = useFindFirst(api.shopifyShop, {
    select: { id: true, verificationCode: true, finalized: true },
  });
  const { appBridge } = useGadget();

  useEffect(() => {
    if (!data?.finalized && appBridge && !fetching && data?.id) {
      const url = new URL("https://showday.io/signup");
      const params = new URLSearchParams();
      params.append("verificationCode", data?.verificationCode || "");
      params.append("shopId", data?.id);
      url.search = params.toString();

      Redirect.create(appBridge).dispatch(
        Redirect.Action.REMOTE,
        url.toString()
      );
    }
  }, [data, appBridge, fetching]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Showday Sample App</h1>

        <div className={styles.grid}>
          {fetching && <Spinner $size={SIZE.small} />}
          {data?.finalized && <Finalized />}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

const Home: NextPage = () => {
  const { loading, isAuthenticated } = useGadget();

  return !loading && isAuthenticated ? (
    <Authenticated />
  ) : (
    <Spinner $size={SIZE.medium} />
  );
};

export default Home;
